{
 "title": "blackbox",
 "description": "blackbox1",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "项目",
    "query": "label_values(probe_success, project)"
   },
   {
    "name": "server",
    "label": "主机",
    "query": "label_values(probe_success{project=~\"$project\"}, server)"
   },
   {
    "name": "instance",
    "label": "实例",
    "query": "label_values(probe_success{project=~\"$project\",server=~\"$server\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "总耗时",
   "type": "graph",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{project=~\"$project\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "阶段耗时",
   "type": "graph",
   "gridPos": { "h": 13, "w": 13, "x": 11, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{project=~\"$project\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{phase}}"
    },
    {
     "expr": "probe_http_duration_seconds{project=~\"$project\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{phase}}"
    },
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{project=~\"$project\",instance=~\"$instance\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "sum by (phase) (probe_icmp_duration_seconds{project=~\"$project\",instance=~\"$instance\"})",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "状态明细",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "probe_success{project=~\"$project\",instance=~\"$instance\"} - 0"
    },
    {
     "expr": "probe_http_ssl{project=~\"$project\",instance=~\"$instance\"} - 0"
    },
    {
     "expr": "probe_http_status_code{project=~\"$project\",instance=~\"$instance\"} - 0"
    },
    {
     "expr": "probe_ssl_earliest_cert_expiry{project=~\"$project\",instance=~\"$instance\"} - time()"
    }
   ]
  }
 ]
}